name: Build
on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    paths-ignore:
      - "ReadMe.md"
      - ".gitignore"
      - ".editorconfig"
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - "ReadMe.md"
      - ".gitignore"
      - ".editorconfig"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Build
        run: dotnet publish -c Release
